//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IsoSec.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="IsoSecParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IIsoSecVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] IsoSecParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeName([NotNull] IsoSecParser.TypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.funcDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDeclaration([NotNull] IsoSecParser.FuncDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.declararionArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclararionArgs([NotNull] IsoSecParser.DeclararionArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] IsoSecParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.decLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecLine([NotNull] IsoSecParser.DecLineContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>returnStat</c>
	/// labeled alternative in <see cref="IsoSecParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStat([NotNull] IsoSecParser.ReturnStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>decStat</c>
	/// labeled alternative in <see cref="IsoSecParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecStat([NotNull] IsoSecParser.DecStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ctrlStat</c>
	/// labeled alternative in <see cref="IsoSecParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCtrlStat([NotNull] IsoSecParser.CtrlStatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>expStat</c>
	/// labeled alternative in <see cref="IsoSecParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpStat([NotNull] IsoSecParser.ExpStatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.compName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompName([NotNull] IsoSecParser.CompNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.declarationBase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationBase([NotNull] IsoSecParser.DeclarationBaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] IsoSecParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>if</c>
	/// labeled alternative in <see cref="IsoSecParser.ctrlStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] IsoSecParser.IfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>while</c>
	/// labeled alternative in <see cref="IsoSecParser.ctrlStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] IsoSecParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>doWhile</c>
	/// labeled alternative in <see cref="IsoSecParser.ctrlStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoWhile([NotNull] IsoSecParser.DoWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>for</c>
	/// labeled alternative in <see cref="IsoSecParser.ctrlStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor([NotNull] IsoSecParser.ForContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.ifElse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElse([NotNull] IsoSecParser.IfElseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse([NotNull] IsoSecParser.ElseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp([NotNull] IsoSecParser.ExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.compVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompVar([NotNull] IsoSecParser.CompVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] IsoSecParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.atomVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomVar([NotNull] IsoSecParser.AtomVarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar([NotNull] IsoSecParser.VarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc([NotNull] IsoSecParser.FuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] IsoSecParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConst([NotNull] IsoSecParser.ConstContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsoSecParser.newObj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewObj([NotNull] IsoSecParser.NewObjContext context);
}
